'use strict';

const VERSION='7.1.0';
const BRAND='Pace & Page';
const SUBJECTS=['物理','生化','生物','化學','英文'];
const SUBJECT_TOTALS={物理:105,生物:177,生化:129,化學:104,英文:0};
const SUBJECT_COLORS={物理:'var(--physics)',生化:'var(--biochem)',生物:'var(--biology)',化學:'var(--chem)',英文:'var(--english)',其他:'var(--blue)'};
const LS={settings:'studyos_v7_settings',cache:'studyos_v7_cache',local:'studyos_v7_local',focus:'studyos_v7_focus',theme:'studyos_theme'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0');
const now=()=>new Date();
const isoDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const startOfDay=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const startOfWeek=d=>{const x=startOfDay(d);return addDays(x,-((x.getDay()+6)%7))};
const endOfWeek=d=>addDays(startOfWeek(d),6);
const minFmt=m=>{m=Math.max(0,Math.round(Number(m)||0));const h=Math.floor(m/60),r=m%60;return h?`${h}h${r?` ${r}m`:''}`:`${r}m`};
const pct=(a,b)=>b?Math.round(a/b*100):0;
const uid=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const get=(o,keys,def='')=>{for(const k of keys){if(o&&o[k]!==undefined&&o[k]!==null&&String(o[k])!=='')return o[k]}return def};
const nget=(o,keys)=>Number(get(o,keys,0))||0;
const parseDate=v=>{if(!v)return null;if(v instanceof Date)return v;const s=String(v).trim();let d=new Date(s);if(!isNaN(d))return d;const m=s.match(/(\d{4})[-\/]?(\d{1,2})[-\/]?(\d{1,2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null};
const sameDay=(a,b)=>isoDate(a)===isoDate(b);

let cloud={activityLog:[],manualProgress:[],quickLog:[],questionLog:[],vocabulary:[],weeklyPlan:[],decisionLog:[],planBoard:[]};
let local=loadJSON(LS.local,{vocabulary:[],weeklyPlan:[],decisionLog:[],planBoard:[],pendingActions:[],templates:[],ui:{studyTab:'courses',insightRange:'week',planMode:'list',courseSubject:'物理'}});
local.vocabulary=local.vocabulary||[];local.weeklyPlan=local.weeklyPlan||[];local.decisionLog=local.decisionLog||[];local.planBoard=local.planBoard||[];local.pendingActions=local.pendingActions||[];local.templates=local.templates||[];local.ui=local.ui||{};
let settings=loadJSON(LS.settings,{apiUrl:'',token:'',examDate:'',reviewReminders:false,reviewStartDate:'',reviewIntervals:[1,3,7,14,30],weekTarget:25,dayCapacity:6});
if(!settings._v71ReviewMigrated){settings.reviewReminders=false;settings.reviewStartDate='';settings._v71ReviewMigrated=true;saveSettings()}
let currentView='today',undoAction=null,toastTimer=null,wakeLock=null;
let focus={running:false,paused:false,minimized:false,startedAt:null,durationMin:50,remainingSec:3000,subject:'',topic:'',activity:'專注',mode:'quick',planId:'',tick:null};

function loadJSON(k,d){try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}}
function saveLocal(){localStorage.setItem(LS.local,JSON.stringify(local))}
function saveSettings(){localStorage.setItem(LS.settings,JSON.stringify(settings));try{sessionStorage.setItem(LS.settings,JSON.stringify(settings))}catch{}}
function cacheCloud(){localStorage.setItem(LS.cache,JSON.stringify({time:new Date().toISOString(),...cloud}))}
function loadCache(){const c=loadJSON(LS.cache,null);if(c)Object.assign(cloud,c)}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem(LS.theme,theme);document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#0e1622':'#eef3f8'}
function initTheme(){setTheme(localStorage.getItem(LS.theme)||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'))}

function cleanTopic(raw,subject=''){
  let s=String(raw||'').trim();
  s=s.replace(new RegExp(`^${subject}_?`),'');
  s=s.replace(/^\d{1,3}(?:-\d+)?_?/,'');
  s=s.replace(/_?20\d{6}$/,'');
  s=s.replace(/【[^】]+】/g,'');
  s=s.replace(/^(?:筆記|NOTE)[-_\s]*/i,'');
  s=s.replace(/_{2,}/g,' ').replace(/_/g,' ').replace(/\s{2,}/g,' ').trim();
  return s||'未命名項目';
}
function extractCode(raw){const s=String(raw||'');const m=s.match(/(?:^|_)(\d{1,3}(?:-\d+)?)(?:_|\b)/);return m?m[1]:''}
function displayTitle(r){const code=extractCode(r.topic),topic=cleanTopic(r.topic,r.subject);return code?`${r.subject} ${code}｜${topic}`:`${r.subject}｜${topic||r.activity}`}
function displayPlanTitle(p){const code=extractCode(p.topic),topic=cleanTopic(p.topic,p.subject);return code?`${p.subject} ${code}｜${topic}`:`${p.subject}｜${topic||p.activity||'計畫'}`}
function timeLabel(start,end,mins){const f=v=>{const d=parseDate(v);return d?`${pad(d.getHours())}:${pad(d.getMinutes())}`:''};const a=f(start),b=f(end);return a?(b?`${a}–${b}`:a):minFmt(mins)}

function normalizedQuick(r){
  const date=isoDate(parseDate(get(r,['date','日期','start_time','updated_at']))||now());
  return {id:String(get(r,['event_id','id'],uid('q'))),kind:'DONE',date,subject:String(get(r,['subject','科目'],'其他')),activity:String(get(r,['activity','活動','type'],'學習')),topic:String(get(r,['topic','主題','title'],'')).trim(),minutes:nget(r,['minutes','actual_minutes','實際分鐘','分鐘']),status:String(get(r,['status','完成狀態'],'完成')),start:get(r,['start_time','開始時間'],''),end:get(r,['end_time','結束時間'],''),understanding:get(r,['understanding','理解度'],''),notes:get(r,['notes','note','備註'],''),source:'quick',raw:r};
}
function normalizedActivity(r){
  const rawTitle=String(get(r,['title','event_title','標題','summary'],'')).trim(),parts=rawTitle.split('｜');
  const marker=String(get(r,['kind','type','calendar_type','event_type','分類'],'')).toUpperCase()||(rawTitle.includes('｜PLAN｜')?'PLAN':rawTitle.includes('｜DONE｜')?'DONE':'');
  const kind=marker.includes('PLAN')?'PLAN':marker.includes('DONE')?'DONE':String(get(r,['status'],'')).includes('預定')?'PLAN':'DONE';
  const subject=String(get(r,['subject','科目'],parts.length>2?parts[2]:'其他')),activity=String(get(r,['activity','活動'],parts.length>3?parts[3]:(kind==='PLAN'?'計畫':'學習'))),topic=String(get(r,['topic','主題'],parts.length>4?parts.slice(4).join('｜'):''));
  const date=isoDate(parseDate(get(r,['date','日期','start','start_time','開始時間','updated_at']))||now());
  const mins=kind==='PLAN'?nget(r,['minutes','planned_minutes','預計分鐘','plan_minutes']):nget(r,['actual_minutes','minutes','實際分鐘']);
  return {id:String(get(r,['web_event_id','event_id','id'],uid('a'))),kind,date,subject,activity,topic,minutes:mins,status:String(get(r,['status','完成狀態'],kind==='PLAN'?'預定':'完成')),start:get(r,['start_time','start','開始時間'],''),end:get(r,['end_time','end','結束時間'],''),understanding:get(r,['understanding','理解度'],''),notes:get(r,['notes','note','備註'],''),source:'activity',raw:r};
}
function allRecords(){
  const arr=[...cloud.activityLog.map(normalizedActivity),...cloud.quickLog.map(normalizedQuick)],seen=new Set(),out=[];
  for(const r of arr){const sig=r.id&&!r.id.startsWith('a_')&&!r.id.startsWith('q_')?r.id:[r.kind,r.date,r.subject,r.activity,r.topic,r.minutes].join('|');if(seen.has(sig))continue;seen.add(sig);out.push(r)}
  return out.sort((a,b)=>(String(a.date)+String(a.start)).localeCompare(String(b.date)+String(b.start)));
}
function doneRecords(){return allRecords().filter(x=>x.kind==='DONE')}
function externalPlanRecords(){return allRecords().filter(x=>x.kind==='PLAN')}
function sumMin(rows){return rows.reduce((s,r)=>s+(Number(r.minutes)||0),0)}
function subjectMinutes(rows){const m={};SUBJECTS.forEach(s=>m[s]=0);rows.forEach(r=>m[r.subject]=(m[r.subject]||0)+(Number(r.minutes)||0));return m}
function activityMinutes(rows){const m={};rows.forEach(r=>{const k=r.activity||'其他';m[k]=(m[k]||0)+(Number(r.minutes)||0)});return m}
function between(date,from,to){return date>=isoDate(from)&&date<=isoDate(to)}
function recordsRange(from,to){return doneRecords().filter(r=>between(r.date,from,to))}

function mergeById(localArr,cloudArr){const map=new Map();[...(localArr||[]),...(cloudArr||[])].forEach(x=>{if(x&&x.id)map.set(String(x.id),x)});return [...map.values()]}
function mergedVocabulary(){return mergeById(local.vocabulary,cloud.vocabulary)}
function mergedWeeklyPlan(){return mergeById(local.weeklyPlan,cloud.weeklyPlan)}
function mergedDecisions(){return mergeById(local.decisionLog,cloud.decisionLog).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')))}
function mergedPlanBoard(){return mergeById(local.planBoard,cloud.planBoard).filter(x=>x.status!=='deleted')}
function weekPlanItems(base=now()){const ws=isoDate(startOfWeek(base));return mergedWeeklyPlan().filter(x=>x.week_start===ws)}
function planBoardForDay(date){return mergedPlanBoard().filter(p=>p.bucket==='day'&&p.date===date&&p.status!=='cancelled')}
function planBoardForBucket(bucket,base=now()){const ws=isoDate(startOfWeek(base)),nws=isoDate(addDays(startOfWeek(base),7));return mergedPlanBoard().filter(p=>p.status!=='cancelled'&&(bucket==='week'?p.bucket==='week'&&p.week_start===ws:bucket==='next_week'?p.bucket==='week'&&p.week_start===nws:p.bucket===bucket))}
function isPlanMatched(p,board){return board.some(b=>b.date===p.date&&b.subject===p.subject&&cleanTopic(b.topic,b.subject)===cleanTopic(p.topic,p.subject)&&Math.abs((Number(b.planned_minutes)||0)-(Number(p.minutes)||0))<=5)}
function plansForDay(date){const board=planBoardForDay(date),external=externalPlanRecords().filter(p=>p.date===date&&!isPlanMatched(p,board)).map(p=>({...p,external:true,planned_minutes:p.minutes}));return [...board,...external].sort((a,b)=>String(a.start_time||a.start||'99:99').localeCompare(String(b.start_time||b.start||'99:99')))}
function planMinutes(p){return Number(p.planned_minutes??p.minutes)||0}
function isPlanDone(p,date=p.date){if(p.status==='done')return true;return doneRecords().some(d=>d.date===date&&d.subject===p.subject&&cleanTopic(d.topic,d.subject)===cleanTopic(p.topic,p.subject))}

function currentWeekStats(base=now()){
  const s=startOfWeek(base),e=endOfWeek(base),done=recordsRange(s,e),targets=weekPlanItems(base),targetMin=targets.reduce((a,x)=>a+Number(x.planned_minutes||0),0),subj=subjectMinutes(done);
  const q=cloud.questionLog.filter(r=>{const d=isoDate(parseDate(get(r,['date'],''))||new Date(0));return between(d,s,e)}),qt=q.reduce((a,r)=>a+nget(r,['total_questions']),0),qc=q.reduce((a,r)=>a+nget(r,['correct']),0);
  return{s,e,done,doneMin:sumMin(done),subj,targets,targetMin,questions:qt,accuracy:qt?Math.round(qc/qt*100):0};
}
function todayStats(){const d=isoDate(now()),done=doneRecords().filter(r=>r.date===d),plans=plansForDay(d);return{date:d,done,plans,doneMin:sumMin(done),subj:subjectMinutes(done),remaining:plans.filter(p=>!isPlanDone(p,d)),planMin:plans.reduce((a,p)=>a+planMinutes(p),0)}}

function vocabDue(){const d=isoDate(now());return mergedVocabulary().filter(v=>!truthy(v.mastered)&&(!v.due||v.due<=d)).sort((a,b)=>String(a.due||'').localeCompare(String(b.due||'')))}
function truthy(v){return v===true||String(v).toLowerCase()==='true'||String(v)==='1'}
function reviewQueue(){
  if(!settings.reviewReminders||!settings.reviewStartDate)return[];
  const start=settings.reviewStartDate,today=startOfDay(now()),intervals=settings.reviewIntervals||[1,3,7,14,30],base=new Map();
  doneRecords().filter(r=>r.date>=start&&SUBJECTS.includes(r.subject)&&r.topic&&!String(r.activity).includes('複習')).forEach(r=>{const k=`${r.subject}|${cleanTopic(r.topic,r.subject)}`;if(!base.has(k)||r.date<base.get(k).date)base.set(k,r)});
  const out=[];base.forEach(r=>intervals.forEach((days,idx)=>{const due=addDays(parseDate(r.date),days);if(due>addDays(today,3))return;const reviewed=doneRecords().some(x=>x.date>=start&&x.subject===r.subject&&String(x.activity).includes('複習')&&cleanTopic(x.topic,x.subject)===cleanTopic(r.topic,r.subject)&&parseDate(x.date)>=due);if(!reviewed)out.push({id:`${r.id}_${days}`,subject:r.subject,topic:r.topic,stage:idx+1,due:isoDate(due),overdue:due<today})}));
  return out.sort((a,b)=>a.due.localeCompare(b.due));
}

function nextAction(){
  const t=todayStats();if(t.remaining.length){const p=t.remaining[0];return{label:displayPlanTitle(p),sub:`Today · ${minFmt(planMinutes(p))}`,subject:p.subject,topic:p.topic,activity:p.activity||'學習',planId:p.external?'':p.id}}
  const week=planBoardForBucket('week');if(week.length){const p=week[0];return{label:displayPlanTitle(p),sub:`This Week · ${minFmt(planMinutes(p))}`,subject:p.subject,topic:p.topic,activity:p.activity||'學習',planId:p.id}}
  if(settings.reviewReminders){const rq=reviewQueue().filter(x=>x.overdue);if(rq.length)return{label:`${rq[0].subject}｜${cleanTopic(rq[0].topic,rq[0].subject)}`,sub:'到期複習',subject:rq[0].subject,topic:rq[0].topic,activity:'複習'}}
  return{label:'Quick Focus',sub:'沒有排定項目，直接開始一段專注',subject:'',topic:'',activity:'專注'};
}
function studyBrief(){
  const w=currentWeekStats();if(!w.doneMin&&!w.targetMin)return'這週還沒有資料。先開始一段 Focus，Pace & Page 會慢慢長出你的節奏。';
  let out=`本週已完成 ${minFmt(w.doneMin)}。`;
  if(w.targetMin){out+=`週目標 ${minFmt(w.targetMin)}，目前 ${pct(w.doneMin,w.targetMin)}%。`;const gaps=SUBJECTS.map(s=>{const target=Number(w.targets.find(x=>x.subject===s)?.planned_minutes)||0;return{s,d:(w.subj[s]||0)-target,target}}).filter(x=>x.target>0);const low=gaps.sort((a,b)=>a.d-b.d)[0],high=gaps.sort((a,b)=>b.d-a.d)[0];if(low&&low.d<-30)out+=`${low.s}比目標少 ${minFmt(Math.abs(low.d))}。`;if(high&&high.d>60)out+=`${high.s}投入比目標多 ${minFmt(high.d)}。`}
  else out+='尚未設定 Weekly Targets，所以不計算執行率。';
  if(settings.reviewReminders){const n=reviewQueue().filter(x=>x.overdue).length;if(n)out+=`目前有 ${n} 項複習逾期。`}
  return out;
}
function examPhase(){if(!settings.examDate)return{label:'未設定考試日',sub:'More → Settings 可設定'};const ex=parseDate(settings.examDate),days=Math.ceil((startOfDay(ex)-startOfDay(now()))/86400000);if(days<0)return{label:'考試日已過',sub:`${Math.abs(days)} days ago`};return{label:days>180?'正課建立期':days>90?'整合複習期':days>30?'考古題強化期':'考前衝刺期',sub:`D−${days} · ${settings.examDate}`}}

function courseStatusMap(){const m=new Map();cloud.manualProgress.forEach(r=>{const s=String(get(r,['subject'],'')),c=String(get(r,['code'],''));if(s&&c)m.set(`${s}|${c}`,r)});return m}
const PHYSICS_CATALOG=[['001-1','軌跡方程式'],['001-2','牛頓三定律'],['002-1','七大外力'],['002-2','木塊運動'],['003-1','滑輪系統'],['003-2','圓周運動與向心力'],['004-1','彈力位能'],['004-2','保守力與非保守力'],['005-1','機械能守恆'],['005-2','質心運動'],['006-1','動量守恆'],['006-2','火箭問題'],['007-1','質心運動與力矩'],['007-2','功的種類'],['008-1','轉動與滾動'],['008-2','轉動與滾動'],['009-1','角動量與角動量守恆'],['009-2','陀螺問題'],['010-1','斜拋運動'],['010-2','單擺'],['011-1','熱與熱力學'],['011-2','熱與熱力學'],['012-1','等壓過程'],['012-2','絕熱過程'],['013-1','各式引擎'],['013-2','熵增原理'],['014-1','熱傳導'],['014-2','重力場與重力位能'],['015-1','重力位能'],['015-2','克卜勒三定律'],['016-1','庫倫定律'],['016-2','庫倫定律'],['017-2','高斯定律'],['018-1','導體與電場'],['018-2','導體與電場'],['020-1','電容器'],['021-1','介電質'],['021-2','動電學'],['022-1','RC 電路'],['022-2','RC 電路'],['023-1','磁場'],['023-2','磁偶極矩'],['024-2','安培定律'],['025-1','修正安培定律與位移電流']];
function trackedCourses(){
  const map=new Map(),status=courseStatusMap();
  PHYSICS_CATALOG.forEach(([code,topic])=>map.set(`物理|${code}`,{subject:'物理',code,type:'正課',topic,status:'未開始',progress:0,recent:''}));
  cloud.manualProgress.forEach(r=>{const subject=String(get(r,['subject'],'')),code=String(get(r,['code'],''));if(!subject||!code)return;const k=`${subject}|${code}`,old=map.get(k)||{};map.set(k,{...old,subject,code,type:String(get(r,['course_type'],'正課')),topic:old.topic||String(get(r,['topic','description'],'課程')),status:String(get(r,['status'],'已看課')),progress:nget(r,['progress'])||45,recent:String(get(r,['recent'],''))})});
  allRecords().forEach(r=>{if(!SUBJECTS.includes(r.subject)||!r.topic)return;const code=extractCode(r.topic);if(!code)return;const k=`${r.subject}|${code}`,old=map.get(k)||{};const st=status.get(k);map.set(k,{...old,subject:r.subject,code,type:old.type||r.activity||'正課',topic:old.topic||cleanTopic(r.topic,r.subject),status:st?String(get(st,['status'],'已看課')):(r.kind==='DONE'?'已看課':old.status||'未開始'),progress:st?nget(st,['progress']):(r.kind==='DONE'?45:Number(old.progress)||0),recent:st?String(get(st,['recent'],'')):(r.kind==='DONE'?r.date:old.recent||'')})});
  return [...map.values()].sort((a,b)=>SUBJECTS.indexOf(a.subject)-SUBJECTS.indexOf(b.subject)||String(a.code).localeCompare(String(b.code),undefined,{numeric:true}));
}
function subjectProgress(subject){const tracked=trackedCourses().filter(x=>x.subject===subject&&Number(x.progress)>0),total=SUBJECT_TOTALS[subject]||tracked.length;if(!total)return 0;return Math.min(100,Math.round(tracked.reduce((a,x)=>a+(Number(x.progress)||0),0)/(total*100)*100))}

function render(){renderNav();({today:renderToday,plan:renderPlan,study:renderStudy,insights:renderInsights,more:renderMore}[currentView]||renderToday)();updateFocusUI()}
function renderNav(){
  $$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===currentView));$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${currentView}`)?.classList.add('active');
  const meta={today:['PACE & PAGE · TODAY','今天，只看下一步。'],plan:['PLAN · REALITY','把一週排得剛剛好。'],study:['STUDY WORKSPACE','讀書的內容，留在這裡。'],insights:['INSIGHTS','先看結論，再看數據。'],more:['PACE & PAGE · MORE','設定、歷史與備考決策。']}[currentView];$('#eyebrow').textContent=meta[0];$('#pageTitle').textContent=meta[1];
}
function subjectPills(subj){return SUBJECTS.map(s=>`<div class="subject-pill" data-subject="${s}"><b>${s}</b><small>${minFmt(subj[s]||0)}</small></div>`).join('')}
function renderToday(){
  const t=todayStats(),w=currentWeekStats(),na=nextAction(),phase=examPhase(),doneCount=t.plans.filter(p=>isPlanDone(p,t.date)).length;
  const tasks=t.plans.length?t.plans.map(planTaskHTML).join(''):`<div class="empty-state"><b>今天還沒有 PLAN</b>可以直接開始 Focus，或把 This Week 的項目移到今天。</div>`;
  const reviewN=settings.reviewReminders?reviewQueue().filter(x=>x.overdue).length:0;
  $('#view-today').innerHTML=`
    <div class="today-layout">
      <div class="card paper-card focus-hero"><span class="tape"></span>
        <div><div class="section-label">TODAY FOCUS</div><div class="big-time">${minFmt(t.doneMin)}</div><div class="subline">${t.plans.length?`${doneCount}/${t.plans.length} tasks completed`:'No plan required · Quick Focus anytime'}</div></div>
        <div><div class="subject-strip">${subjectPills(t.subj)}</div><div class="hero-actions"><button class="pill-btn primary" data-action="focus-preset" data-min="50">▶ 50 min Focus</button><button class="pill-btn" data-action="focus-picker">其他時間</button><button class="pill-btn" data-action="historical">＋ 補記</button></div></div>
      </div>
      <div class="card paper-card next-paper"><span class="tape right small"></span><div class="hand-note">下一步，不必想太多。</div>
        <div class="next-card"><b>${esc(na.label)}</b><small>${esc(na.sub)}</small><div class="actions"><button class="tiny-btn go" data-action="next-focus">Start Focus</button>${na.planId?`<button class="tiny-btn" data-action="move-plan" data-id="${esc(na.planId)}" data-dest="tomorrow">明天</button>`:''}</div></div>
        <div class="micro-kpis"><div class="micro-kpi"><span>This week</span><b>${minFmt(w.doneMin)}</b></div><div class="micro-kpi"><span>Words due</span><b>${vocabDue().length}</b></div><div class="micro-kpi"><span>${settings.reviewReminders?'Review due':'Exam'}</span><b>${settings.reviewReminders?reviewN:(settings.examDate?phase.sub.split(' · ')[0]:'—')}</b></div></div>
      </div>
    </div>
    <div class="spacer"></div>
    <div class="grid grid-2">
      <div class="card pad paper-card"><div class="section-head"><h2 class="display-font">Today Plan</h2><div><button class="text-btn" data-action="day-close">Day Close</button> · <button class="text-btn" data-action="add-plan" data-bucket="today">＋ 安排</button></div></div><div class="task-list">${tasks}</div></div>
      <div class="grid"><div class="card pad"><div class="section-label">STUDY BRIEF</div><div class="brief"><strong>本週節奏</strong><p>${esc(studyBrief())}</p></div></div><div class="card pad"><div class="section-head"><h3>Quick move</h3><small>待安排 → 今天</small></div>${quickMoveHTML()}</div></div>
    </div>
    <div class="spacer"></div>
    <div class="card pad"><div class="section-head"><h2 class="display-font">Today Timeline</h2><button class="text-btn" data-action="history">History</button></div>${renderTimeline(t.done)}</div>`;
}
function planTaskHTML(p){const done=isPlanDone(p,p.date),id=p.id||'',mins=planMinutes(p);return`<div class="task ${done?'done':''}"><button class="task-check" data-action="complete-plan" data-id="${esc(id)}" data-external="${p.external?'1':'0'}">✓</button><div class="task-main"><b>${esc(displayPlanTitle(p))}</b><small>${esc(p.activity||'學習')} · ${minFmt(mins)}${p.start_time||p.start?` · ${timeLabel(p.start_time||p.start,'',mins)}`:''}${p.external?' · Calendar':''}</small></div><div class="task-actions"><button class="tiny-btn go" data-action="task-focus" data-id="${esc(id)}" data-external="${p.external?'1':'0'}">Focus</button>${!p.external?`<button class="tiny-btn" data-action="move-plan" data-id="${esc(id)}" data-dest="tomorrow">明天</button><button class="more-btn" data-action="plan-menu" data-id="${esc(id)}">⋯</button>`:`<button class="more-btn" data-action="record-menu" data-source="activity" data-id="${esc(p.id)}" data-kind="PLAN">⋯</button>`}</div></div>`}
function quickMoveHTML(){const inbox=planBoardForBucket('inbox').slice(0,3),week=planBoardForBucket('week').slice(0,3),items=[...inbox,...week].slice(0,4);if(!items.length)return`<div class="empty-state"><b>沒有待安排項目</b>想到什麼先丟進 Inbox，不必立刻決定日期。</div>`;return`<div class="task-list">${items.map(p=>`<div class="task"><div></div><div class="task-main"><b>${esc(displayPlanTitle(p))}</b><small>${p.bucket==='inbox'?'Inbox':'This Week'} · ${minFmt(planMinutes(p))}</small></div><div class="task-actions"><button class="tiny-btn go" data-action="move-plan" data-id="${esc(p.id)}" data-dest="today">今天</button></div></div>`).join('')}</div>`}
function renderTimeline(rows){if(!rows.length)return`<div class="empty-state"><b>今天還沒有時間軸</b>Focus 完成或補記後會出現在這裡。</div>`;return`<div class="timeline-list">${rows.slice().sort((a,b)=>String(a.start).localeCompare(String(b.start))).map(r=>`<div class="timeline-item"><div class="timeline-time">${timeLabel(r.start,r.end,r.minutes)}</div><div class="timeline-line"></div><div class="timeline-body"><b>${esc(displayTitle(r))}</b><small>${esc(r.activity)} · ${minFmt(r.minutes)}${r.understanding?` · 理解 ${esc(r.understanding)}/5`:''}</small></div><button class="more-btn" data-action="record-menu" data-source="${r.source}" data-id="${esc(r.id)}" data-kind="DONE">⋯</button></div>`).join('')}</div>`}

function renderPlan(){
  const today=isoDate(now()),tomorrow=isoDate(addDays(now(),1)),todayPlans=plansForDay(today),tomorrowPlans=plansForDay(tomorrow),inbox=planBoardForBucket('inbox'),week=planBoardForBucket('week'),nextWeek=planBoardForBucket('next_week'),mode=local.ui.planMode||'list';
  const todayMin=todayPlans.filter(p=>!isPlanDone(p,today)).reduce((a,p)=>a+planMinutes(p),0),capacity=Math.round((Number(settings.dayCapacity)||6)*60),capPct=Math.min(100,pct(todayMin,capacity));
  const w=currentWeekStats(),wp=weekPlanItems();
  $('#view-plan').innerHTML=`
    <div class="grid grid-3">
      <div class="card pad"><div class="section-label">TODAY CAPACITY</div><div class="capacity" style="margin-top:13px"><div class="capacity-ring" style="--capacity:${capPct}%"><b>${capPct}%</b></div><div class="capacity-copy"><b>${minFmt(todayMin)} planned / ${minFmt(capacity)} available</b><small>${todayMin>capacity?`超出 ${minFmt(todayMin-capacity)}，今天可能排得太滿。`:`還有 ${minFmt(Math.max(0,capacity-todayMin))} 可安排。`}</small></div></div></div>
      <div class="card metric-card emphasis"><span>THIS WEEK</span><b>${minFmt(w.doneMin)}</b><small>${w.targetMin?`Target ${minFmt(w.targetMin)} · ${pct(w.doneMin,w.targetMin)}%`:'尚未設定 Weekly Targets'}</small></div>
      <div class="card pad"><div class="section-label">PLANNING MODE</div><div class="segmented" style="margin-top:12px"><button data-action="plan-mode" data-mode="list" class="${mode==='list'?'active':''}">List</button><button data-action="plan-mode" data-mode="timeline" class="${mode==='timeline'?'active':''}">Timeline</button></div><div class="hero-actions" style="margin-top:12px"><button class="pill-btn" data-action="template" data-template="full">全日讀書日</button><button class="pill-btn" data-action="template" data-template="half">半日讀書日</button></div></div>
    </div>
    <div class="spacer"></div>
    <div class="plan-columns">
      ${planColumn('Inbox','先收進來，不急著決定哪天',inbox,'inbox')}
      ${planColumn('Today',`${new Date().getMonth()+1}/${new Date().getDate()} · ${minFmt(todayMin)}`,todayPlans,'today')}
      ${planColumn('Tomorrow',`${addDays(now(),1).getMonth()+1}/${addDays(now(),1).getDate()}`,tomorrowPlans,'tomorrow')}
    </div>
    <div class="spacer"></div>
    <div class="grid grid-2">
      ${planColumn('This Week','本週想完成，但還沒指定日期',week,'week')}
      ${planColumn('Next Week','先放著，下週再排',nextWeek,'next_week')}
    </div>
    <div class="spacer"></div>
    <div class="grid grid-2"><div class="card pad"><div class="section-head"><h2 class="display-font">Plan vs Reality</h2><button class="text-btn" data-action="weekly-target">設定目標</button></div>${weeklyTargetsHTML(w,wp)}</div><div class="card pad"><div class="section-head"><h2 class="display-font">Weekly Note</h2></div><div class="stat-note">${esc(weeklyInsight(w))}</div></div></div>`;
}
function planColumn(title,sub,items,bucket){const timeline=(local.ui.planMode||'list')==='timeline'&&['today','tomorrow'].includes(bucket);return`<div class="card plan-column paper-card ${timeline?'timeline-mode':''}"><div class="col-head"><div><h3>${esc(title)}</h3><span>${esc(sub)}</span></div><button class="text-btn" data-action="add-plan" data-bucket="${bucket}">＋</button></div><div class="plan-drop">${items.length?(timeline?planTimelineHTML(items,bucket):items.map(p=>planCardHTML(p,bucket)).join('')):`<div class="empty-state">目前是空的</div>`}</div></div>`}
function planTimelineHTML(items,bucket){const sorted=[...items].sort((a,b)=>String(a.start_time||a.start||'99:99').localeCompare(String(b.start_time||b.start||'99:99')));return`<div class="plan-timeline">${sorted.map(p=>{const t=p.start_time||p.start||'',time=t?timeLabel(t,'',planMinutes(p)):'未排時間',done=bucket==='today'&&isPlanDone(p,isoDate(now()));return`<div class="plan-time-row ${done?'done':''}"><div class="plan-time">${esc(time)}</div><span class="plan-time-dot" style="--dot:${SUBJECT_COLORS[p.subject]||'var(--blue)'}"></span><div class="plan-time-card"><b>${esc(displayPlanTitle(p))}</b><small>${esc(p.activity||'學習')} · ${minFmt(planMinutes(p))}</small><div class="plan-buttons">${bucket==='today'?`<button class="tiny-btn go" data-action="task-focus" data-id="${esc(p.id||'')}" data-external="${p.external?'1':'0'}">Focus</button>`:''}${!p.external?`<button class="more-btn" data-action="plan-menu" data-id="${esc(p.id||'')}">⋯</button>`:`<button class="more-btn" data-action="record-menu" data-source="activity" data-id="${esc(p.id)}" data-kind="PLAN">⋯</button>`}</div></div></div>`}).join('')}</div>`}
function planCardHTML(p,bucket){const done=bucket==='today'&&isPlanDone(p,isoDate(now()));return`<div class="plan-card ${done?'done':''}"><button class="more-btn" data-action="plan-menu" data-id="${esc(p.id||'')}" ${p.external?'data-external="1"':''}>⋯</button><b>${esc(displayPlanTitle(p))}</b><small>${esc(p.activity||'學習')} · ${minFmt(planMinutes(p))}${p.start_time||p.start?` · ${timeLabel(p.start_time||p.start,'',planMinutes(p))}`:''}</small><div class="plan-buttons">${bucket!=='today'?`<button class="tiny-btn go" data-action="move-plan" data-id="${esc(p.id||'')}" data-dest="today" ${p.external?'disabled':''}>今天</button>`:''}${bucket!=='tomorrow'?`<button class="tiny-btn" data-action="move-plan" data-id="${esc(p.id||'')}" data-dest="tomorrow" ${p.external?'disabled':''}>明天</button>`:''}${bucket==='today'?`<button class="tiny-btn go" data-action="task-focus" data-id="${esc(p.id||'')}" data-external="${p.external?'1':'0'}">Focus</button>`:''}</div></div>`}
function weeklyTargetsHTML(w,wp){if(!wp.length)return`<div class="empty-state"><b>Weekly Targets 尚未設定</b>設定後才會計算週執行率，不會再出現失真的 467%。</div>`;return`<div class="weekly-bars">${SUBJECTS.map(s=>{const target=Number(wp.find(x=>x.subject===s)?.planned_minutes)||0,actual=w.subj[s]||0,max=Math.max(target,actual,1);return`<div class="weekly-row"><span>${s}</span><div class="bar-track"><i style="width:${Math.min(100,actual/max*100)}%;background:${SUBJECT_COLORS[s]}"></i></div><b>${minFmt(actual)} / ${minFmt(target)}</b></div>`}).join('')}</div>`}
function weeklyInsight(w){if(!w.targetMin)return`本週已完成 ${minFmt(w.doneMin)}。先設定科目目標後，這裡會顯示「哪科偏多、哪科偏少」，而不是只給一個百分比。`;const diffs=SUBJECTS.map(s=>{const t=Number(w.targets.find(x=>x.subject===s)?.planned_minutes)||0;return{s,d:(w.subj[s]||0)-t,t}}).filter(x=>x.t>0),high=[...diffs].sort((a,b)=>b.d-a.d)[0],low=[...diffs].sort((a,b)=>a.d-b.d)[0];let x=`這週完成 ${minFmt(w.doneMin)} / ${minFmt(w.targetMin)}。`;if(high?.d>45)x+=`${high.s}比目標多 ${minFmt(high.d)}。`;if(low?.d<-45)x+=`${low.s}比目標少 ${minFmt(Math.abs(low.d))}。`;return x}

function renderStudy(){
  const allowed=['courses','questions','vocab','history',...(settings.reviewReminders?['reviews']:[])];if(!allowed.includes(local.ui.studyTab))local.ui.studyTab='courses';const tab=local.ui.studyTab;
  $('#view-study').innerHTML=`<div class="tabs">${[['courses','Courses'],['questions','Questions'],['vocab','Vocabulary'],['history','History'],...(settings.reviewReminders?[['reviews','Review']]:[])].map(([k,v])=>`<button data-study-tab="${k}" class="${tab===k?'active':''}">${v}</button>`).join('')}</div><div class="spacer"></div><div id="studyBody"></div>`;renderStudyBody(tab);
}
function renderStudyBody(tab){const el=$('#studyBody');if(!el)return;if(tab==='courses')el.innerHTML=renderCourses();else if(tab==='questions')el.innerHTML=renderQuestions();else if(tab==='vocab')el.innerHTML=renderVocab();else if(tab==='history')el.innerHTML=renderHistory();else if(tab==='reviews')el.innerHTML=renderReviews()}
function renderCourses(){const subj=local.ui.courseSubject||'物理',items=trackedCourses().filter(x=>x.subject===subj),started=items.filter(x=>Number(x.progress)>0).length;return`<div class="grid grid-4">${SUBJECTS.slice(0,4).map(s=>`<div class="card metric-card"><span>${s}</span><b>${subjectProgress(s)}%</b><small>${trackedCourses().filter(x=>x.subject===s&&Number(x.progress)>0).length} tracked / ${SUBJECT_TOTALS[s]} total</small></div>`).join('')}</div><div class="spacer"></div><div class="card pad"><div class="section-head"><h2 class="display-font">Courses</h2><button class="text-btn" data-action="manual-progress">＋ 補進度</button></div><div class="course-toolbar"><select class="select" id="courseSubject">${SUBJECTS.slice(0,4).map(s=>`<option ${s===subj?'selected':''}>${s}</option>`).join('')}</select><div class="search-field"><input id="courseSearch" placeholder="搜尋堂次或主題"></div></div><div class="muted" style="font-size:10px;margin-bottom:12px">${subj}：${started} 筆已有狀態。顯示名稱會自動清除底線、日期與【其他】等原始標籤。</div><div class="course-grid" id="courseGrid">${courseCards(items)}</div></div>`}
function courseCards(items){if(!items.length)return`<div class="empty-state"><b>還沒有這科的課程紀錄</b>可以用「補進度」加入，或同步現有 ActivityLog。</div>`;return items.map(c=>`<div class="course-card"><span class="course-code">${esc(c.subject)} ${esc(c.code)}</span><b>${esc(cleanTopic(c.topic,c.subject))}</b><small><i class="status-dot ${Number(c.progress)>=45?'done':Number(c.progress)>0?'progress':''}"></i>${esc(c.status||'未開始')} · ${Number(c.progress)||0}%</small><div class="course-actions"><button class="tiny-btn go" data-action="course-focus" data-subject="${esc(c.subject)}" data-code="${esc(c.code)}" data-topic="${esc(c.topic)}">Focus</button>${settings.reviewReminders?`<button class="tiny-btn" data-action="course-review" data-subject="${esc(c.subject)}" data-topic="${esc(c.topic)}">複習</button>`:''}</div></div>`).join('')}
function renderQuestions(){const rows=[...cloud.questionLog].sort((a,b)=>String(b.date).localeCompare(String(a.date))),total=rows.reduce((a,r)=>a+nget(r,['total_questions']),0),correct=rows.reduce((a,r)=>a+nget(r,['correct']),0);return`<div class="grid grid-3"><div class="card metric-card emphasis"><span>累積題數</span><b>${total}</b><small>${rows.length} sessions</small></div><div class="card metric-card"><span>整體正確率</span><b>${total?Math.round(correct/total*100):'—'}${total?'%':''}</b><small>題量與正確率一起看</small></div><div class="card metric-card"><span>待回看</span><b>${rows.filter(r=>!truthy(r.reviewed)&&nget(r,['wrong'])>0).length}</b><small>有錯題的紀錄</small></div></div><div class="spacer"></div><div class="card pad"><div class="section-head"><h2 class="display-font">Question Log</h2><button class="text-btn" data-action="add-question">＋ 刷題</button></div>${rows.length?`<div class="task-list">${rows.slice(0,60).map(q=>`<div class="task"><div></div><div class="task-main"><b>${esc(q.subject)}｜${esc(q.source||q.topic||'刷題')}</b><small>${esc(q.date)} · ${nget(q,['total_questions'])} 題 · ${nget(q,['accuracy'])}%${q.error_type?` · ${esc(q.error_type)}`:''}</small></div><div class="task-actions"><button class="more-btn" data-action="question-menu" data-id="${esc(q.id)}">⋯</button></div></div>`).join('')}</div>`:`<div class="empty-state">尚無刷題紀錄</div>`}</div>`}
function renderVocab(){const words=mergedVocabulary(),due=vocabDue(),mastered=words.filter(v=>truthy(v.mastered)).length,learning=words.filter(v=>!truthy(v.mastered)&&Number(v.interval_step||0)>0).length;return`<div class="grid grid-4"><div class="card metric-card emphasis"><span>Due today</span><b>${due.length}</b><small>現在真正需要看的字</small></div><div class="card metric-card"><span>New</span><b>${words.filter(v=>!v.last_reviewed).length}</b><small>尚未第一次複習</small></div><div class="card metric-card"><span>Learning</span><b>${learning}</b><small>正在間隔複習</small></div><div class="card metric-card"><span>Mastered</span><b>${mastered}</b><small>已熟練</small></div></div><div class="spacer"></div><div class="card pad"><div class="section-head"><h2 class="display-font">Vocabulary</h2><div><button class="text-btn" data-action="vocab-review">Review</button> · <button class="text-btn" data-action="vocab-add">＋ Word</button></div></div><div class="vocab-list">${words.length?words.slice().sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||''))).map(v=>`<div class="vocab-row"><div><b>${esc(v.word)}</b><small>${esc(v.meaning||'尚未補意思')} ${v.source?`· ${esc(v.source)}`:''}</small></div><button class="more-btn" data-action="vocab-menu" data-id="${esc(v.id)}">⋯</button></div>`).join(''):`<div class="empty-state"><b>先快速收第一個字</b>閱讀時只輸入 Word 就能先存。</div>`}</div></div>`}
function renderHistory(){const rows=doneRecords().slice().sort((a,b)=>(String(b.date)+String(b.start)).localeCompare(String(a.date)+String(a.start)));return`<div class="card pad"><div class="section-head"><h2 class="display-font">History</h2><button class="text-btn" data-action="historical">＋ 補記</button></div><div class="course-toolbar"><div class="search-field"><input id="historySearch" placeholder="搜尋日期、科目、內容"></div><select class="select" id="historySubject"><option value="">全部科目</option>${SUBJECTS.map(s=>`<option>${s}</option>`).join('')}</select></div><div id="historyRows">${historyRowsHTML(rows)}</div></div>`}
function historyRowsHTML(rows){if(!rows.length)return`<div class="empty-state">還沒有學習紀錄</div>`;return`<div class="timeline-list">${rows.slice(0,120).map(r=>`<div class="timeline-item"><div class="timeline-time">${esc(r.date.slice(5))}<br>${timeLabel(r.start,r.end,r.minutes)}</div><div class="timeline-line"></div><div class="timeline-body"><b>${esc(displayTitle(r))}</b><small>${esc(r.activity)} · ${minFmt(r.minutes)}${r.source==='activity'?' · Calendar':''}</small></div><button class="more-btn" data-action="record-menu" data-source="${r.source}" data-id="${esc(r.id)}" data-kind="DONE">⋯</button></div>`).join('')}</div>`}
function renderReviews(){if(!settings.reviewReminders)return`<div class="card pad"><div class="empty-state"><b>Review 目前關閉</b>啟用後只會從啟用日開始建立複習排程，不會把過去所有課一次變成欠帳。</div></div>`;const q=reviewQueue(),today=isoDate(now()),over=q.filter(x=>x.due<today),due=q.filter(x=>x.due===today),up=q.filter(x=>x.due>today);return`<div class="grid grid-3">${reviewGroup('Today',due)}${reviewGroup('Overdue',over)}${reviewGroup('Upcoming',up)}</div>`}
function reviewGroup(title,items){return`<div class="card pad"><div class="section-head"><h3>${title}</h3><small>${items.length}</small></div>${items.length?`<div class="task-list">${items.slice(0,20).map(x=>`<div class="task"><div></div><div class="task-main"><b>${esc(x.subject)}｜${esc(cleanTopic(x.topic,x.subject))}</b><small>R${x.stage} · ${esc(x.due)}</small></div><div class="task-actions"><button class="tiny-btn go" data-action="finish-review" data-subject="${esc(x.subject)}" data-topic="${esc(x.topic)}">完成</button></div></div>`).join('')}</div>`:`<div class="empty-state">沒有項目</div>`}</div>`}

function rangeConfig(key){const end=startOfDay(now());if(key==='day')return{from:end,to:end,prevFrom:addDays(end,-1),prevTo:addDays(end,-1),days:1,label:'Today'};if(key==='month'){const from=new Date(end.getFullYear(),end.getMonth(),1),prevEnd=addDays(from,-1),prevFrom=new Date(prevEnd.getFullYear(),prevEnd.getMonth(),1);return{from,to:end,prevFrom,prevTo:prevEnd,days:Math.max(1,Math.round((end-from)/86400000)+1),label:'Month'}};if(key==='90'){return{from:addDays(end,-89),to:end,prevFrom:addDays(end,-179),prevTo:addDays(end,-90),days:90,label:'90 Days'}};const from=startOfWeek(end);return{from,to:end,prevFrom:addDays(from,-7),prevTo:addDays(end,-7),days:7,label:'Week'}}
function renderInsights(){
  const key=local.ui.insightRange||'week',cfg=rangeConfig(key),rows=recordsRange(cfg.from,cfg.to),prev=recordsRange(cfg.prevFrom,cfg.prevTo),total=sumMin(rows),prevTotal=sumMin(prev),delta=total-prevTotal,subj=subjectMinutes(rows),acts=activityMinutes(rows),q=cloud.questionLog.filter(r=>between(String(r.date||''),cfg.from,cfg.to)),qt=q.reduce((a,r)=>a+nget(r,['total_questions']),0),qc=q.reduce((a,r)=>a+nget(r,['correct']),0),focusRows=rows.filter(r=>String(r.notes||'').includes('[focus]'));
  const summary=insightSummary(key,rows,prev,subj);
  $('#view-insights').innerHTML=`<div class="insight-head"><div><div class="headline">${minFmt(total)}</div><div class="muted" style="font-size:11px">${cfg.label} · ${rows.length} records</div></div><div class="segmented">${[['day','DAY'],['week','WEEK'],['month','MONTH'],['90','90 DAYS']].map(([k,v])=>`<button data-range="${k}" class="${key===k?'active':''}">${v}</button>`).join('')}</div></div><div class="spacer"></div><div class="grid grid-4"><div class="card metric-card emphasis"><span>Study time</span><b>${minFmt(total)}</b><small class="delta ${delta>=0?'up':'down'}">${delta>=0?'＋':'−'}${minFmt(Math.abs(delta))} vs previous</small></div><div class="card metric-card"><span>Avg / day</span><b>${minFmt(total/Math.max(1,cfg.days))}</b><small>${cfg.days} day window</small></div><div class="card metric-card"><span>Questions</span><b>${qt}</b><small>${qt?`${Math.round(qc/qt*100)}% correct`:'尚無題目紀錄'}</small></div><div class="card metric-card"><span>Focus sessions</span><b>${focusRows.length}</b><small>${focusRows.length?`avg ${minFmt(sumMin(focusRows)/focusRows.length)}`:'Focus 完成後會累積'}</small></div></div><div class="spacer"></div><div class="card pad"><div class="stat-note">${esc(summary)}</div></div><div class="spacer"></div><div class="grid grid-2"><div class="card pad"><div class="chart-title">時間花在哪一科？</div><div class="chart-question">固定科目顏色 · 點數字可看明細</div>${hbarHTML(subj,total,'subject')}</div><div class="card pad"><div class="chart-title">時間花在哪一種活動？</div><div class="chart-question">看課、刷題、英文等一眼比較</div>${hbarHTML(acts,total,'activity')}</div></div><div class="spacer"></div><div class="card pad"><div class="chart-title">最近每天讀多久？</div><div class="chart-question">柱狀圖優先，避免不易比較的圓餅圖</div>${dailyBarsHTML(cfg.from,cfg.to)}</div><div class="spacer"></div><div class="grid grid-2"><div class="card pad"><div class="chart-title">Plan vs Actual</div><div class="chart-question">只使用你設定的 Weekly Targets，不拿零碎 Calendar PLAN 硬算</div>${key==='week'?weeklyTargetsHTML(currentWeekStats(),weekPlanItems()):`<div class="empty-state">切到 WEEK 看本週差距</div>`}</div><div class="card pad"><div class="chart-title">Study Heatmap</div><div class="chart-question">深淺只代表學習量，不做焦慮式打卡</div>${heatmapHTML(70)}</div></div>`;
}
function insightSummary(key,rows,prev,subj){if(!rows.length)return'這段期間還沒有紀錄。數據頁會先保持安靜，不用硬製造結論。';const total=sumMin(rows),p=sumMin(prev),top=SUBJECTS.map(s=>({s,m:subj[s]||0})).sort((a,b)=>b.m-a.m)[0],w=currentWeekStats();let x=`${key==='week'?'這週':'這段期間'}共 ${minFmt(total)}，${p?`${total>=p?'比前一期多':'比前一期少'} ${minFmt(Math.abs(total-p))}`:'目前沒有可比較的前一期資料'}。`;if(top?.m)x+=`${top.s}投入最多（${minFmt(top.m)}）。`;if(key==='week'&&w.targetMin){const gap=w.targetMin-w.doneMin;x+=gap>0?`距離週目標還有 ${minFmt(gap)}。`:`已超過週目標 ${minFmt(Math.abs(gap))}。`}return x}
function hbarHTML(obj,total,type){const entries=Object.entries(obj).filter(([,m])=>m>0).sort((a,b)=>b[1]-a[1]);if(!entries.length)return`<div class="empty-state">沒有資料</div>`;const max=Math.max(...entries.map(x=>x[1]),1);return`<div class="hbars">${entries.map(([k,m])=>`<div class="hbar"><span>${esc(k)}</span><div class="hbar-track"><i style="width:${m/max*100}%;background:${type==='subject'?(SUBJECT_COLORS[k]||'var(--blue)'):'var(--blue)'}"></i></div><button data-action="insight-detail" data-type="${type}" data-key="${esc(k)}">${minFmt(m)}</button></div>`).join('')}</div>`}
function dailyBarsHTML(from,to){const days=[];for(let d=new Date(from);d<=to;d=addDays(d,1))days.push(new Date(d));const vals=days.map(d=>sumMin(doneRecords().filter(r=>r.date===isoDate(d)))),max=Math.max(...vals,1);return`<div class="daily-bars">${days.map((d,i)=>`<div class="day-col"><div class="bar" style="height:${Math.max(3,vals[i]/max*150)}px" data-label="${minFmt(vals[i])}"></div><small>${d.getMonth()+1}/${d.getDate()}</small></div>`).join('')}</div>`}
function heatmapHTML(n){const days=[...Array(n)].map((_,i)=>addDays(now(),-(n-1-i))),vals=days.map(d=>sumMin(doneRecords().filter(r=>r.date===isoDate(d)))),max=Math.max(...vals,1);return`<div class="heatmap">${days.map((d,i)=>{const p=vals[i]/max,l=p===0?'':p<.25?'l1':p<.5?'l2':p<.75?'l3':'l4';return`<div class="heat-cell ${l}" title="${isoDate(d)} · ${minFmt(vals[i])}"></div>`}).join('')}</div>`}

function renderMore(){const phase=examPhase();$('#view-more').innerHTML=`<div class="grid grid-2"><div class="card pad paper-card"><span class="tape small"></span><div class="section-head"><h2 class="display-font">Settings</h2></div><div class="form"><div class="field"><label>Apps Script Web App URL</label><input id="settingUrl" value="${esc(settings.apiUrl||'')}" placeholder="https://script.google.com/.../exec"></div><div class="field"><label>同步密鑰</label><input id="settingToken" type="password" value="${esc(settings.token||'')}" placeholder="只存在你的瀏覽器"></div><div class="form-row"><div class="field"><label>考試日期</label><input id="settingExam" type="date" value="${esc(settings.examDate||'')}"></div><div class="field"><label>每日可用時數</label><input id="settingCapacity" type="number" step="0.5" min="1" max="16" value="${Number(settings.dayCapacity)||6}"></div></div><div class="form-actions"><button data-action="test-sync">測試同步</button><button class="save" data-action="save-settings">儲存</button></div></div></div><div class="card pad"><div class="section-head"><h2 class="display-font">Roadmap</h2></div><div class="brief"><strong>${esc(phase.label)}</strong><p>${esc(phase.sub)}</p></div><div class="divider"></div><div class="section-head"><h3>Review Module</h3><small>${settings.reviewReminders?'ON':'OFF'}</small></div><p class="muted" style="font-size:11px;line-height:1.6">預設關閉。啟用時只從啟用日開始建立複習排程，不追溯舊課造成大量 backlog。</p><button class="soft-btn" data-action="toggle-review">${settings.reviewReminders?'關閉複習功能':'啟用複習功能'}</button></div></div><div class="spacer"></div><div class="grid grid-2"><div class="card pad"><div class="section-head"><h2 class="display-font">Decision Log</h2><button class="text-btn" data-action="add-decision">＋ 決策</button></div>${mergedDecisions().length?`<div class="task-list">${mergedDecisions().slice(0,20).map(d=>`<div class="task"><div></div><div class="task-main"><b>${esc(d.title)}</b><small>${esc(d.reason||'')} ${d.review_date?`· Review ${esc(d.review_date)}`:''}</small></div></div>`).join('')}</div>`:`<div class="empty-state">只記真正會影響策略的大決定。</div>`}</div><div class="card pad"><div class="section-head"><h2 class="display-font">Data & Backup</h2></div><div class="brief"><strong>${local.pendingActions.length} 筆待同步</strong><p>離線時先存在本機，下一次同步會重送。</p></div><div class="divider"></div><button class="soft-btn" data-action="history">開啟 History Center</button> <button class="soft-btn" data-action="export-backup">下載 Backup</button><p class="muted" style="font-size:10px;margin-top:14px">${BRAND} ${VERSION} · 無 AI API / token。</p></div></div>`}

function openSheet(html){$('#sheetContent').innerHTML=html;$('#sheetBackdrop').classList.add('show');$('#bottomSheet').classList.add('show')}
function closeSheet(){$('#sheetBackdrop').classList.remove('show');$('#bottomSheet').classList.remove('show')}
function sheetTitle(t,sub=''){return`<div class="sheet-title"><div><h2>${esc(t)}</h2>${sub?`<small class="muted">${esc(sub)}</small>`:''}</div><button data-action="close-sheet">×</button></div>`}
function openQuickMenu(){openSheet(`${sheetTitle('Quick Add','常用操作控制在 1–2 次點擊')}<div class="action-grid"><button class="action-card" data-action="focus-picker"><b>◷ Start Focus</b><small>先計時，完成後再記內容</small></button><button class="action-card" data-action="add-plan" data-bucket="inbox"><b>＋ Study Inbox</b><small>先記下來，之後再排日期</small></button><button class="action-card" data-action="add-plan" data-bucket="today"><b>◫ Today Plan</b><small>安排今天</small></button><button class="action-card" data-action="add-plan" data-bucket="week"><b>□ This Week</b><small>這週想完成，不指定日期</small></button><button class="action-card" data-action="historical"><b>＋ 補記完成</b><small>今天 / 昨天 / 前天 / 其他日期</small></button><button class="action-card" data-action="add-question"><b>✓ 刷題</b><small>快速記題數與答對數</small></button><button class="action-card" data-action="vocab-add"><b>Aa 單字</b><small>先收字，細節之後再補</small></button><button class="action-card" data-action="manual-progress"><b>▤ 課程進度</b><small>補以前已完成的課</small></button></div>`)}
function openFocusPicker(){openSheet(`${sheetTitle('Start Focus','Quick Focus 可以做完再分類')}<div class="quick-picks">${[25,45,50,60,90].map(m=>`<button data-action="focus-preset" data-min="${m}">${m} min</button>`).join('')}</div><div class="spacer"></div><div class="form-row"><div class="field"><label>科目（可留空）</label><select id="focusPickSubject"><option value="">Quick Focus</option>${SUBJECTS.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="field"><label>自訂分鐘</label><input id="focusCustomMin" type="number" min="1" max="240" value="50"></div></div><div class="form-actions"><button class="save" data-action="focus-custom">開始</button></div>`)}
async function requestWakeLock(){try{if('wakeLock' in navigator&&document.visibilityState==='visible')wakeLock=await navigator.wakeLock.request('screen')}catch{}}
async function releaseWakeLock(){try{if(wakeLock){await wakeLock.release();wakeLock=null}}catch{}}
function startFocus(min,subject='',topic='',activity='專注',mode='quick',planId=''){closeSheet();focus={running:true,paused:false,minimized:false,startedAt:new Date().toISOString(),durationMin:Number(min)||50,remainingSec:(Number(min)||50)*60,subject,topic,activity,mode,planId,tick:null};saveFocus();showFocus(false);requestWakeLock();runFocusTick()}
function saveFocus(){localStorage.setItem(LS.focus,JSON.stringify({...focus,tick:null,savedAt:Date.now()}))}
function loadFocus(){const f=loadJSON(LS.focus,null);if(!f||!f.running)return;focus={...focus,...f};if(!focus.paused&&focus.startedAt){const elapsed=Math.round((Date.now()-new Date(f.startedAt).getTime())/1000);focus.remainingSec=Math.max(0,focus.durationMin*60-elapsed)}showFocus(!!focus.minimized);requestWakeLock();runFocusTick()}
function showFocus(minimized=false){focus.minimized=minimized;saveFocus();$('#focusLayer').classList.toggle('show',!minimized);$('#focusLayer').setAttribute('aria-hidden',minimized?'true':'false');$('#miniFocus').classList.toggle('show',minimized);$('#miniFocus').setAttribute('aria-hidden',minimized?'false':'true');$('#focusSubject').textContent=focus.subject||'Quick Focus';$('#focusTopic').textContent=focus.topic?cleanTopic(focus.topic,focus.subject):'結束後再紀錄內容';updateFocusUI()}
function runFocusTick(){clearInterval(focus.tick);focus.tick=setInterval(()=>{if(focus.running&&!focus.paused){focus.remainingSec=Math.max(0,focus.remainingSec-1);saveFocus();updateFocusUI();if(focus.remainingSec<=0){clearInterval(focus.tick);try{navigator.vibrate?.([120,80,120])}catch{}finishFocus(true)}}},1000)}
function updateFocusUI(){if(!focus.running)return;const m=Math.floor(focus.remainingSec/60),s=focus.remainingSec%60,text=`${pad(m)}:${pad(s)}`,p=Math.max(0,Math.min(100,(focus.durationMin*60-focus.remainingSec)/(focus.durationMin*60)*100));if($('#focusClock'))$('#focusClock').textContent=text;if($('#miniFocusTime'))$('#miniFocusTime').textContent=text;if($('#miniFocusLabel'))$('#miniFocusLabel').textContent=focus.subject?(focus.topic?`${focus.subject} · ${cleanTopic(focus.topic,focus.subject)}`:focus.subject):'Quick Focus';if($('#clockProgress'))$('#clockProgress').style.setProperty('--p',`${p}%`);if($('#focusPause'))$('#focusPause').textContent=focus.paused?'Resume':'Pause';if($('#miniPause'))$('#miniPause').textContent=focus.paused?'▶':'Ⅱ';if($('#focusStatus'))$('#focusStatus').textContent=focus.paused?'Paused':'專注中'}
function addFocusMinutes(n){focus.remainingSec+=n*60;focus.durationMin+=n;saveFocus();updateFocusUI()}
function toggleFocusPause(){focus.paused=!focus.paused;if(!focus.paused)focus.startedAt=new Date(Date.now()-(focus.durationMin*60-focus.remainingSec)*1000).toISOString();saveFocus();updateFocusUI()}
function cancelFocus(){if(!confirm('要取消這次 Focus 嗎？這段時間不會寫入紀錄。'))return;clearInterval(focus.tick);focus.running=false;localStorage.removeItem(LS.focus);releaseWakeLock();showFocus(false);$('#focusLayer').classList.remove('show');$('#miniFocus').classList.remove('show')}
function finishFocus(completed=false){clearInterval(focus.tick);const elapsed=Math.max(1,Math.round((focus.durationMin*60-focus.remainingSec)/60));const pref={minutes:completed?focus.durationMin:elapsed,subject:focus.subject,topic:focus.topic,activity:focus.activity,focus:true,planId:focus.planId};focus.running=false;localStorage.removeItem(LS.focus);releaseWakeLock();$('#focusLayer').classList.remove('show');$('#miniFocus').classList.remove('show');openDoneForm(pref)}

function openDoneForm(pref={}){const today=isoDate(now()),d=pref.date||today,last=local.lastDone||{},subject=pref.subject??last.subject??'',activity=pref.activity||last.activity||'專注',minutes=Number(pref.minutes||last.minutes)||50,record=pref.record||{};openSheet(`${sheetTitle(record.id?'修改紀錄':pref.focus?'Focus 完成':'補記完成',record.id?'修改後會同步到原紀錄':'會正確算進該日與該週統計')}<div class="form"><input type="hidden" id="doneRecordId" value="${esc(record.id||'')}"><input type="hidden" id="doneRecordSource" value="${esc(record.source||'quick')}"><input type="hidden" id="donePlanId" value="${esc(pref.planId||'')}"><div class="field"><label>日期</label><div class="quick-picks"><button data-set-date="${today}" class="${d===today?'active':''}">今天</button><button data-set-date="${isoDate(addDays(now(),-1))}">昨天</button><button data-set-date="${isoDate(addDays(now(),-2))}">前天</button></div><input id="doneDate" type="date" value="${esc(record.date||d)}"></div><div class="form-row"><div class="field"><label>科目</label><select id="doneSubject">${['其他',...SUBJECTS].map(s=>`<option ${s===(record.subject||subject)?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>類型</label><select id="doneActivity">${['看課','複習','刷題','英文閱讀','單字','專注','其他'].map(s=>`<option ${s===(record.activity||activity)?'selected':''}>${s}</option>`).join('')}</select></div></div><div class="field"><label>內容</label><input id="doneTopic" value="${esc(record.topic??pref.topic??'')}" placeholder="例如：正課 27 / Vol.06 Day 02"></div><div class="form-row"><div class="field"><label>實際分鐘</label><input id="doneMinutes" type="number" min="1" max="600" value="${Number(record.minutes||minutes)}"><div class="quick-picks">${[30,45,50,60,90].map(m=>`<button data-set-minutes="${m}">${m}</button>`).join('')}</div></div><div class="field"><label>理解度（選填）</label><select id="doneUnderstanding"><option value="">不填</option>${[1,2,3,4,5].map(x=>`<option ${String(record.understanding||'')===String(x)?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="field"><label>備註</label><textarea id="doneNotes">${esc(record.notes||(pref.focus?'[focus]':''))}</textarea></div><div class="form-actions"><button data-action="close-sheet">取消</button>${!record.id&&!pref.focus?`<button data-action="save-done-more">儲存＋再新增</button>`:''}<button class="save" data-action="save-done">${record.id?'儲存修改':'儲存 DONE'}</button></div></div>`)}
function openPlanForm(bucket='today',pref={}){const today=isoDate(now()),tomorrow=isoDate(addDays(now(),1)),isEdit=!!pref.id;let date=pref.date||'';if(!date&&bucket==='today')date=today;if(!date&&bucket==='tomorrow')date=tomorrow;const ws=bucket==='next_week'?isoDate(addDays(startOfWeek(now()),7)):isoDate(startOfWeek(now()));openSheet(`${sheetTitle(isEdit?'修改 PLAN':'新增 PLAN','Inbox / Today / Tomorrow / This Week 都可互相移動')}<div class="form"><input type="hidden" id="planId" value="${esc(pref.id||'')}"><div class="field"><label>放在哪裡</label><select id="planBucket"><option value="inbox" ${bucket==='inbox'?'selected':''}>Inbox</option><option value="today" ${bucket==='today'?'selected':''}>Today</option><option value="tomorrow" ${bucket==='tomorrow'?'selected':''}>Tomorrow</option><option value="week" ${bucket==='week'?'selected':''}>This Week</option><option value="next_week" ${bucket==='next_week'?'selected':''}>Next Week</option><option value="date" ${bucket==='date'?'selected':''}>指定日期</option></select></div><div class="form-row"><div class="field"><label>日期（Today/Tomorrow 會自動帶入）</label><input id="planDate" type="date" value="${esc(date)}"></div><div class="field"><label>科目</label><select id="planSubject">${SUBJECTS.map(s=>`<option ${s===pref.subject?'selected':''}>${s}</option>`).join('')}</select></div></div><div class="field"><label>內容</label><input id="planTopic" value="${esc(pref.topic||'')}" placeholder="例如：物理正課 28"></div><div class="form-row"><div class="field"><label>類型</label><select id="planActivity">${['看課','複習','刷題','英文閱讀','單字','其他'].map(s=>`<option ${s===pref.activity?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>預計分鐘</label><input id="planMinutes" type="number" min="1" value="${Number(pref.planned_minutes||pref.minutes||60)}"></div></div><div class="field"><label>開始時間（可留空）</label><input id="planStartTime" type="time" value="${esc(pref.start_time||'')}"></div><input type="hidden" id="planWeekStart" value="${ws}"><div class="form-actions"><button data-action="close-sheet">取消</button><button class="save" data-action="save-plan">儲存 PLAN</button></div></div>`)}
function openPlanMenu(id){const p=mergedPlanBoard().find(x=>String(x.id)===String(id));if(!p)return;openSheet(`${sheetTitle('Plan actions',displayPlanTitle(p))}<div class="action-grid"><button class="action-card" data-action="edit-plan" data-id="${esc(id)}"><b>修改</b><small>科目、內容、時間、日期</small></button><button class="action-card" data-action="move-plan" data-id="${esc(id)}" data-dest="today"><b>移到今天</b><small>直接加入 Today</small></button><button class="action-card" data-action="move-plan" data-id="${esc(id)}" data-dest="tomorrow"><b>移到明天</b><small>不用刪掉重建</small></button><button class="action-card" data-action="move-plan" data-id="${esc(id)}" data-dest="week"><b>放回本週</b><small>先不指定日期</small></button><button class="action-card" data-action="delete-plan" data-id="${esc(id)}"><b style="color:var(--red)">刪除</b><small>會同步移除相關 Calendar PLAN</small></button></div>`)}
function openRecordMenu(source,id,kind='DONE'){const r=allRecords().find(x=>x.source===source&&String(x.id)===String(id));if(!r)return;openSheet(`${sheetTitle('Record actions',displayTitle(r))}<div class="action-grid"><button class="action-card" data-action="edit-record" data-source="${source}" data-id="${esc(id)}"><b>修改紀錄</b><small>日期、科目、內容、分鐘</small></button><button class="action-card" data-action="delete-record" data-source="${source}" data-id="${esc(id)}"><b style="color:var(--red)">刪除紀錄</b><small>${source==='activity'?'同步刪除 Calendar 原事件':'同步刪除 QuickLog + DONE Calendar'}</small></button></div>`)}
function openQuestionForm(id=''){const old=cloud.questionLog.find(x=>String(x.id)===String(id))||{};openSheet(`${sheetTitle(id?'修改刷題':'記錄刷題','題量與正確率一起看')}<div class="form"><input id="qId" type="hidden" value="${esc(old.id||'')}"><div class="form-row"><div class="field"><label>日期</label><input id="qDate" type="date" value="${esc(old.date||isoDate(now()))}"></div><div class="field"><label>科目</label><select id="qSubject">${SUBJECTS.map(s=>`<option ${s===old.subject?'selected':''}>${s}</option>`).join('')}</select></div></div><div class="field"><label>來源 / 主題</label><input id="qSource" value="${esc(old.source||old.topic||'')}" placeholder="例如：112 高醫 / Chapter 3"></div><div class="form-row"><div class="field"><label>總題數</label><input id="qTotal" type="number" min="1" value="${nget(old,['total_questions'])||20}"></div><div class="field"><label>答對</label><input id="qCorrect" type="number" min="0" value="${nget(old,['correct'])||0}"></div></div><div class="field"><label>主要錯因</label><select id="qError"><option value="">不填</option>${['觀念錯','計算錯','看錯題','記憶錯','選項陷阱'].map(x=>`<option ${x===old.error_type?'selected':''}>${x}</option>`).join('')}</select></div><div class="form-actions"><button data-action="close-sheet">取消</button><button class="save" data-action="save-question">儲存</button></div></div>`)}
function openQuestionMenu(id){openSheet(`${sheetTitle('Question actions')}<div class="action-grid"><button class="action-card" data-action="edit-question" data-id="${esc(id)}"><b>修改</b><small>題數、答對、錯因</small></button><button class="action-card" data-action="delete-question" data-id="${esc(id)}"><b style="color:var(--red)">刪除</b><small>刪除這筆刷題紀錄</small></button></div>`)}
function openVocabForm(id=''){const v=mergedVocabulary().find(x=>String(x.id)===String(id))||{};openSheet(`${sheetTitle(id?'編輯單字':'Quick Vocabulary Capture','先快速收，再慢慢整理')}<div class="form"><div class="field"><label>Word</label><input id="vWord" value="${esc(v.word||'')}" autofocus placeholder="mitigate"></div><div class="field"><label>Meaning</label><input id="vMeaning" value="${esc(v.meaning||'')}" placeholder="減輕、緩和"></div><div class="field"><label>Source</label><input id="vSource" value="${esc(v.source||'')}" placeholder="Vol.06 Day 02"></div><div class="field"><label>Sentence / Note</label><textarea id="vSentence">${esc(v.sentence||'')}</textarea></div><input type="hidden" id="vId" value="${esc(v.id||'')}"><div class="form-actions"><button data-action="close-sheet">取消</button><button class="save" data-action="save-vocab">儲存</button></div></div>`)}
function openVocabMenu(id){openSheet(`${sheetTitle('Vocabulary actions')}<div class="action-grid"><button class="action-card" data-action="vocab-edit" data-id="${esc(id)}"><b>修改</b><small>意思、來源、例句</small></button><button class="action-card" data-action="vocab-delete" data-id="${esc(id)}"><b style="color:var(--red)">刪除</b><small>移除這個單字</small></button></div>`)}
function openVocabReview(){const due=vocabDue();if(!due.length){showToast('今天沒有到期單字');return}const v=due[0];openSheet(`${sheetTitle(`Vocabulary · ${due.length} due`,'點卡片顯示答案')}<div class="flashcard" id="flashcard" data-id="${esc(v.id)}"><div><div class="word">${esc(v.word)}</div><div class="answer"><b>${esc(v.meaning||'尚未補意思')}</b><p>${esc(v.sentence||v.source||'')}</p></div></div></div><div class="grade-row"><button data-action="grade-vocab" data-grade="0">不會</button><button data-action="grade-vocab" data-grade="1">模糊</button><button data-action="grade-vocab" data-grade="2">會</button></div>`)}
function openWeeklyTarget(){const current=weekPlanItems(),ws=isoDate(startOfWeek(now()));openSheet(`${sheetTitle('Weekly Targets',ws)}<div class="form">${SUBJECTS.map(s=>`<div class="field"><label>${s} 預計時數</label><input class="weekly-hour" data-subject="${s}" type="number" step="0.5" min="0" value="${((Number(current.find(x=>x.subject===s)?.planned_minutes)||0)/60)||0}"></div>`).join('')}<div class="form-actions"><button data-action="close-sheet">取消</button><button class="save" data-action="save-weekly-target">儲存</button></div></div>`)}
function openManualProgress(){openSheet(`${sheetTitle('補課程進度','只改進度，不虛構讀書時間')}<div class="form"><div class="form-row"><div class="field"><label>科目</label><select id="mSubject">${SUBJECTS.slice(0,4).map(s=>`<option>${s}</option>`).join('')}</select></div><div class="field"><label>課程代碼（可批次）</label><input id="mCode" placeholder="027, 028, 029 或 27-30"></div></div><div class="field"><label>狀態</label><select id="mStatus"><option>已看課</option>${settings.reviewReminders?'<option>第1次複習</option><option>第2次複習</option><option>第3次複習</option>':''}</select></div><div class="form-actions"><button data-action="close-sheet">取消</button><button class="save" data-action="save-manual">儲存進度</button></div></div>`)}
function openDecisionForm(){openSheet(`${sheetTitle('Study Decision','只記會影響備考策略的決定')}<div class="form"><div class="field"><label>決策</label><input id="dTitle"></div><div class="field"><label>原因 / 判斷</label><textarea id="dReason"></textarea></div><div class="field"><label>回看日期</label><input id="dReview" type="date"></div><div class="form-actions"><button data-action="close-sheet">取消</button><button class="save" data-action="save-decision">儲存</button></div></div>`)}
function openDayClose(){const t=todayStats(),left=t.plans.filter(p=>!isPlanDone(p,t.date));openSheet(`${sheetTitle('Day Close',`${minFmt(t.doneMin)} focused · ${t.plans.length-left.length}/${t.plans.length} tasks completed`)}${left.length?`<div class="task-list">${left.map(p=>`<div class="task"><div></div><div class="task-main"><b>${esc(displayPlanTitle(p))}</b><small>${minFmt(planMinutes(p))}</small></div>${p.external?'':`<div class="task-actions"><button class="tiny-btn go" data-action="move-plan" data-id="${esc(p.id)}" data-dest="tomorrow">明天</button><button class="tiny-btn" data-action="move-plan" data-id="${esc(p.id)}" data-dest="week">本週</button></div>`}</div>`).join('')}</div>`:`<div class="empty-state"><b>今天的計畫都處理完了</b>可以直接安排 Tomorrow。</div>`}<div class="form-actions"><button data-action="add-plan" data-bucket="tomorrow" class="save">＋ 安排明天</button></div>`)}
function openGlobalSearch(){openSheet(`${sheetTitle('Search','課程、PLAN、紀錄、單字都可以找')}<div class="search-field"><input id="globalSearchInput" autofocus placeholder="例如：物理 28 / mitigate / 9/8"></div><div class="spacer"></div><div id="globalSearchResults" class="task-list"><div class="empty-state">開始輸入關鍵字</div></div>`)}
function globalSearchHTML(q){q=String(q||'').trim().toLowerCase();if(!q)return`<div class="empty-state">開始輸入關鍵字</div>`;const results=[];trackedCourses().forEach(c=>{const text=`${c.subject} ${c.code} ${c.topic}`.toLowerCase();if(text.includes(q))results.push({type:'Course',title:`${c.subject} ${c.code}｜${cleanTopic(c.topic,c.subject)}`,sub:`${c.status} · ${c.progress}%`})});mergedPlanBoard().forEach(p=>{if(`${p.subject} ${p.topic} ${p.date}`.toLowerCase().includes(q))results.push({type:'Plan',title:displayPlanTitle(p),sub:p.date||p.bucket})});doneRecords().forEach(r=>{if(`${r.date} ${r.subject} ${r.topic}`.toLowerCase().includes(q))results.push({type:'Record',title:displayTitle(r),sub:`${r.date} · ${minFmt(r.minutes)}`})});mergedVocabulary().forEach(v=>{if(`${v.word} ${v.meaning} ${v.source}`.toLowerCase().includes(q))results.push({type:'Word',title:v.word,sub:`${v.meaning||''} ${v.source||''}`})});return results.slice(0,40).map(x=>`<div class="task"><div></div><div class="task-main"><b>${esc(x.title)}</b><small>${esc(x.type)} · ${esc(x.sub)}</small></div></div>`).join('')||`<div class="empty-state">找不到結果</div>`}
function openInsightDetail(type,key){const cfg=rangeConfig(local.ui.insightRange||'week'),rows=recordsRange(cfg.from,cfg.to).filter(r=>type==='subject'?r.subject===key:r.activity===key);openSheet(`${sheetTitle(`${key} · ${minFmt(sumMin(rows))}`,`${cfg.label} 明細`)}${renderTimeline(rows)}`)}

async function syncCloud(force=false){
  if(!settings.apiUrl||!settings.token){setSyncUI('Local only','尚未設定 Apps Script');if(force)showToast('先到 More 設定 Apps Script URL 與同步密鑰');return false}
  setSyncUI('Syncing…','正在讀取雲端');await flushPending();
  try{const cb=`pacePage_${Date.now()}`,url=new URL(settings.apiUrl);url.searchParams.set('action','sync');url.searchParams.set('token',settings.token);url.searchParams.set('callback',cb);if(force)url.searchParams.set('refresh_calendar','1');const data=await jsonp(url.toString(),cb);if(!data.ok)throw new Error(data.error||'sync failed');['activityLog','manualProgress','quickLog','questionLog','vocabulary','weeklyPlan','decisionLog','planBoard'].forEach(k=>cloud[k]=data[k]||[]);cacheCloud();setSyncUI('Synced',`最新 ${new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}`);render();if(force)showToast('同步完成');return true}catch(e){setSyncUI('Sync error',String(e.message||e));if(force)showToast('同步失敗：'+String(e.message||e));return false}}
function jsonp(url,cb){return new Promise((resolve,reject)=>{const s=document.createElement('script');let timer=0;window[cb]=d=>{clearTimeout(timer);delete window[cb];s.remove();resolve(d)};s.src=url;s.onerror=()=>{delete window[cb];s.remove();reject(new Error('network error'))};timer=setTimeout(()=>{delete window[cb];s.remove();reject(new Error('sync timeout'))},15000);document.body.appendChild(s)})}
async function apiPost(action,items){if(!settings.apiUrl||!settings.token)return{ok:false,localOnly:true};const fd=new URLSearchParams();fd.set('payload',JSON.stringify({token:settings.token,action,items}));try{const r=await fetch(settings.apiUrl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:fd,redirect:'follow'});return await r.json()}catch{await fetch(settings.apiUrl,{method:'POST',body:fd,mode:'no-cors',redirect:'follow'});return{ok:true,opaque:true}}}
function queueAction(action,items){local.pendingActions.push({id:uid('pending'),action,items,created_at:new Date().toISOString()});saveLocal()}
async function flushPending(){if(!settings.apiUrl||!settings.token||!local.pendingActions.length)return;const remain=[];for(const p of local.pendingActions){try{const r=await apiPost(p.action,p.items);if(!r.ok&&!r.opaque)remain.push(p)}catch{remain.push(p)}}local.pendingActions=remain;saveLocal()}
function setSyncUI(a,b){$('#syncStatus').textContent=a;$('#lastSync').textContent=b;$('#syncDot').className='sync-dot'+(a.includes('error')?' error':a.includes('Syncing')?' busy':'')}

async function commitDone(data,{keepOpen=false}={}){const {subject='其他',date=isoDate(now()),activity='專注',topic='',minutes=50,understanding='',notes='',planId=''}=data;if(!date||!Number(minutes)){showToast('請填日期與分鐘');return}const d=parseDate(date)||now(),same=isoDate(d)===isoDate(now()),end=same?now():new Date(d.getFullYear(),d.getMonth(),d.getDate(),20,0,0),start=new Date(end.getTime()-Number(minutes)*60000);const item={event_id:uid('web'),date,type:'DONE',subject,activity,topic,minutes:Number(minutes),status:'完成',format:'',source:'Pace & Page',platform:'web',domain:'',understanding,url:'',notes,updated_at:new Date().toISOString(),start_time:start.toISOString(),end_time:end.toISOString(),calendar_event_id:''};cloud.quickLog.push(item);cacheCloud();if(planId)await markPlanDone(planId);render();showToast(`已記錄 ${subject} · ${minFmt(minutes)}`,async()=>{cloud.quickLog=cloud.quickLog.filter(x=>x.event_id!==item.event_id);cacheCloud();render();try{await apiPost('quick_remove',[{event_id:item.event_id,date:item.date}])}catch{queueAction('quick_remove',[{event_id:item.event_id,date:item.date}])}});try{const r=await apiPost('quick_add',[item]);if(!r.ok&&!r.localOnly)throw new Error(r.error||'write failed')}catch{queueAction('quick_add',[item]);showToast('已存本機，待網路恢復後同步')}if(keepOpen)openDoneForm({date,subject,activity,minutes});else closeSheet();return item}
async function saveDone(keepOpen=false){const id=$('#doneRecordId').value,source=$('#doneRecordSource').value||'quick',planId=$('#donePlanId').value,data={subject:$('#doneSubject').value||'其他',date:$('#doneDate').value,activity:$('#doneActivity').value,topic:$('#doneTopic').value.trim(),minutes:Number($('#doneMinutes').value)||0,understanding:$('#doneUnderstanding').value,notes:$('#doneNotes').value,planId};local.lastDone={subject:data.subject,activity:data.activity,minutes:data.minutes};saveLocal();if(!id)return commitDone(data,{keepOpen});await updateDoneRecord(id,source,data);closeSheet();render();showToast('紀錄已更新')}
async function updateDoneRecord(id,source,data){if(source==='quick'){const old=cloud.quickLog.find(x=>String(get(x,['event_id','id'],''))===String(id));if(!old)return;const d=parseDate(data.date),end=sameDay(d,now())?now():new Date(d.getFullYear(),d.getMonth(),d.getDate(),20,0,0),start=new Date(end.getTime()-data.minutes*60000),item={...old,event_id:id,...data,type:'DONE',status:'完成',updated_at:new Date().toISOString(),start_time:start.toISOString(),end_time:end.toISOString()};cloud.quickLog=cloud.quickLog.filter(x=>String(get(x,['event_id','id'],''))!==String(id));cloud.quickLog.push(item);cacheCloud();try{await apiPost('quick_add',[item])}catch{queueAction('quick_add',[item])}}else{const item={event_id:id,...data,type:'DONE',status:'完成',updated_at:new Date().toISOString()};try{const r=await apiPost('activity_update',[item]);if(r.localOnly)throw new Error('needs cloud');await syncCloud(false)}catch{showToast('Calendar 原始紀錄需要連線才能修改')}}}
async function deleteDoneRecord(id,source){if(!confirm('確定刪除這筆紀錄嗎？'))return;closeSheet();if(source==='quick'){const old=cloud.quickLog.find(x=>String(get(x,['event_id','id'],''))===String(id));cloud.quickLog=cloud.quickLog.filter(x=>String(get(x,['event_id','id'],''))!==String(id));cacheCloud();render();showToast('紀錄已刪除',async()=>{if(old){cloud.quickLog.push(old);cacheCloud();render();try{await apiPost('quick_add',[old])}catch{queueAction('quick_add',[old])}}});try{await apiPost('quick_remove',[{event_id:id,date:old?.date||''}])}catch{queueAction('quick_remove',[{event_id:id,date:old?.date||''}])}}else{try{const r=await apiPost('activity_remove',[{event_id:id}]);if(r.localOnly)throw new Error();await syncCloud(false);showToast('Calendar 紀錄已刪除')}catch{showToast('Calendar 原始紀錄需要連線才能刪除')}}}

function planDestination(dest){if(dest==='today')return{bucket:'day',date:isoDate(now()),week_start:isoDate(startOfWeek(now()))};if(dest==='tomorrow')return{bucket:'day',date:isoDate(addDays(now(),1)),week_start:isoDate(startOfWeek(now()))};if(dest==='week')return{bucket:'week',date:'',week_start:isoDate(startOfWeek(now()))};if(dest==='next_week')return{bucket:'week',date:'',week_start:isoDate(addDays(startOfWeek(now()),7))};return{bucket:'inbox',date:'',week_start:''}}
async function upsertPlan(item){local.planBoard=local.planBoard.filter(x=>String(x.id)!==String(item.id));local.planBoard.push(item);saveLocal();render();try{const r=await apiPost('planboard_upsert',[item]);if(!r.ok&&!r.localOnly)throw new Error();if(!r.localOnly)await syncCloud(false)}catch{queueAction('planboard_upsert',[item])}}
async function savePlan(){const id=$('#planId').value||uid('plan'),choice=$('#planBucket').value,base=mergedPlanBoard().find(x=>String(x.id)===String(id))||{},dest=choice==='date'?{bucket:'day',date:$('#planDate').value,week_start:isoDate(startOfWeek(parseDate($('#planDate').value)||now()))}:planDestination(choice),minutes=Number($('#planMinutes').value)||60,time=$('#planStartTime').value||'',item={...base,id,...dest,subject:$('#planSubject').value,activity:$('#planActivity').value,topic:$('#planTopic').value.trim(),planned_minutes:minutes,start_time:time,status:base.status||'open',sort_order:Number(base.sort_order)||Date.now(),created_at:base.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};await upsertPlan(item);closeSheet();showToast('PLAN 已儲存')}
async function movePlan(id,dest){const p=mergedPlanBoard().find(x=>String(x.id)===String(id));if(!p)return;const item={...p,...planDestination(dest),updated_at:new Date().toISOString()};await upsertPlan(item);closeSheet();showToast(dest==='today'?'已移到今天':dest==='tomorrow'?'已移到明天':dest==='week'?'已放回本週':'已移動')}
async function markPlanDone(id){if(!id)return;const p=mergedPlanBoard().find(x=>String(x.id)===String(id));if(!p)return;await upsertPlan({...p,status:'done',updated_at:new Date().toISOString()})}
async function deletePlan(id){if(!confirm('確定刪除這個 PLAN 嗎？'))return;const old=mergedPlanBoard().find(x=>String(x.id)===String(id));local.planBoard=local.planBoard.filter(x=>String(x.id)!==String(id));cloud.planBoard=cloud.planBoard.filter(x=>String(x.id)!==String(id));saveLocal();cacheCloud();closeSheet();render();showToast('PLAN 已刪除',async()=>{if(old)await upsertPlan(old)});try{await apiPost('planboard_remove',[{id}])}catch{queueAction('planboard_remove',[{id}])}}
async function completePlanById(id,external){let p;if(external){p=plansForDay(isoDate(now())).find(x=>x.external&&String(x.id)===String(id))}else p=mergedPlanBoard().find(x=>String(x.id)===String(id));if(!p)return;await commitDone({subject:p.subject,topic:p.topic,activity:p.activity||'學習',minutes:planMinutes(p)||60,date:isoDate(now()),notes:'[plan quick complete]',planId:external?'':p.id})}

async function saveQuestion(){const id=$('#qId').value||uid('q'),total=Number($('#qTotal').value)||0,correct=Math.min(total,Number($('#qCorrect').value)||0);if(!total){showToast('請輸入總題數');return}const old=cloud.questionLog.find(x=>String(x.id)===String(id))||{},item={...old,id,date:$('#qDate').value,subject:$('#qSubject').value,source:$('#qSource').value||'刷題',topic:$('#qSource').value,total_questions:total,correct,wrong:total-correct,accuracy:Math.round(correct/total*100),error_type:$('#qError').value,note:old.note||'',reviewed:old.reviewed||false,reviewed_at:old.reviewed_at||'',updated_at:new Date().toISOString()};cloud.questionLog=cloud.questionLog.filter(x=>String(x.id)!==String(id));cloud.questionLog.push(item);cacheCloud();closeSheet();render();try{await apiPost('question_upsert',[item])}catch{queueAction('question_upsert',[item])}showToast('刷題已儲存')}
async function deleteQuestion(id){if(!confirm('刪除這筆刷題紀錄？'))return;cloud.questionLog=cloud.questionLog.filter(x=>String(x.id)!==String(id));cacheCloud();closeSheet();render();try{await apiPost('question_remove',[{id}])}catch{queueAction('question_remove',[{id}])}showToast('刷題紀錄已刪除')}
function parseCourseCodes(raw){const out=[];String(raw||'').split(/[，,\s]+/).filter(Boolean).forEach(tok=>{const m=tok.match(/^(\d+)-(\d+)$/);if(m&&Number(m[2])>=Number(m[1])&&m[1].length>=2&&m[2].length>=2){const a=Number(m[1]),b=Number(m[2]),width=Math.max(m[1].length,m[2].length);for(let i=a;i<=b&&out.length<100;i++)out.push(String(i).padStart(width,'0'))}else out.push(tok)});return[...new Set(out)]}
async function saveManual(){const subject=$('#mSubject').value,codes=parseCourseCodes($('#mCode').value.trim()),status=$('#mStatus').value;if(!codes.length){showToast('請輸入課程代碼');return}const progress={'已看課':45,'第1次複習':65,'第2次複習':80,'第3次複習':95}[status]||45,items=codes.map(code=>({key:`${subject}|正課|${code}`,subject,course_type:'正課',code,status,progress,recent:isoDate(now()),updated_at:new Date().toISOString()})),keys=new Set(items.map(x=>x.key));cloud.manualProgress=cloud.manualProgress.filter(x=>!keys.has(String(get(x,['key'],''))));cloud.manualProgress.push(...items);cacheCloud();closeSheet();render();try{const r=await apiPost('manual_upsert',items);if(!r.ok&&!r.localOnly)throw new Error()}catch{queueAction('manual_upsert',items)}showToast(`已更新 ${items.length} 堂課程進度`)}
async function saveVocab(){const word=$('#vWord').value.trim();if(!word){showToast('先輸入單字');return}const id=$('#vId').value||uid('vocab'),old=mergedVocabulary().find(v=>String(v.id)===String(id))||{},item={...old,id,word,meaning:$('#vMeaning').value.trim(),source:$('#vSource').value.trim(),sentence:$('#vSentence').value.trim(),level:Number(old.level||0),due:old.due||isoDate(now()),mastered:truthy(old.mastered),interval_step:Number(old.interval_step||0),created_at:old.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};local.vocabulary=local.vocabulary.filter(x=>String(x.id)!==String(id));local.vocabulary.push(item);saveLocal();closeSheet();render();try{await apiPost('vocab_upsert',[item])}catch{queueAction('vocab_upsert',[item])}showToast(`${word} 已儲存`)}
async function deleteVocab(id){if(!confirm('刪除這個單字？'))return;local.vocabulary=local.vocabulary.filter(x=>String(x.id)!==String(id));cloud.vocabulary=cloud.vocabulary.filter(x=>String(x.id)!==String(id));saveLocal();cacheCloud();closeSheet();render();try{await apiPost('vocab_remove',[{id}])}catch{queueAction('vocab_remove',[{id}])}showToast('單字已刪除')}
async function gradeVocab(grade){const id=$('#flashcard')?.dataset.id,item=mergedVocabulary().find(v=>String(v.id)===String(id));if(!item)return;const steps=[1,3,7,14,30];let step=Number(item.interval_step||0);if(grade===0)step=0;else if(grade===2)step=Math.min(steps.length,step+1);item.level=grade;item.interval_step=step;item.last_reviewed=isoDate(now());item.mastered=grade===2&&step>=steps.length;item.due=item.mastered?'':isoDate(addDays(now(),steps[Math.min(step,steps.length-1)]));item.updated_at=new Date().toISOString();local.vocabulary=local.vocabulary.filter(x=>String(x.id)!==String(id));local.vocabulary.push(item);saveLocal();try{await apiPost('vocab_upsert',[item])}catch{queueAction('vocab_upsert',[item])}openVocabReview();render()}
async function saveWeeklyTargets(){const ws=isoDate(startOfWeek(now())),items=$$('.weekly-hour').map(inp=>({id:`${ws}|${inp.dataset.subject}`,week_start:ws,subject:inp.dataset.subject,planned_minutes:Math.round((Number(inp.value)||0)*60),goal:'',updated_at:new Date().toISOString()}));local.weeklyPlan=local.weeklyPlan.filter(x=>x.week_start!==ws);local.weeklyPlan.push(...items);saveLocal();closeSheet();render();try{await apiPost('weekly_upsert',items)}catch{queueAction('weekly_upsert',items)}showToast('Weekly Targets 已更新')}
async function saveDecision(){const title=$('#dTitle').value.trim();if(!title){showToast('請輸入決策');return}const item={id:uid('decision'),title,reason:$('#dReason').value.trim(),review_date:$('#dReview').value,status:'active',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};local.decisionLog.push(item);saveLocal();closeSheet();render();try{await apiPost('decision_upsert',[item])}catch{queueAction('decision_upsert',[item])}showToast('Decision 已儲存')}
function saveSettingsFromForm(){settings.apiUrl=$('#settingUrl').value.trim();settings.token=$('#settingToken').value.trim();settings.examDate=$('#settingExam').value;settings.dayCapacity=Number($('#settingCapacity').value)||6;saveSettings();render();showToast('設定已儲存')}
function toggleReview(){if(settings.reviewReminders){settings.reviewReminders=false;settings.reviewStartDate=''}else{settings.reviewReminders=true;settings.reviewStartDate=isoDate(now())}saveSettings();render();showToast(settings.reviewReminders?`複習功能已啟用，從 ${settings.reviewStartDate} 開始`:'複習功能已關閉')}
function exportBackup(){const blob=new Blob([JSON.stringify({version:VERSION,exported_at:new Date().toISOString(),settings:{...settings,token:''},cloud,local},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Pace_and_Page_v7_1_backup_${isoDate(now())}.json`;a.click();URL.revokeObjectURL(a.href)}
function applyTemplate(name){settings.dayCapacity=name==='full'?8:4;saveSettings();showToast(name==='full'?'已套用全日讀書日：8h capacity':'已套用半日讀書日：4h capacity');render()}
function finishReview(subject,topic){openDoneForm({subject,topic,activity:'複習',minutes:30})}

function showToast(text,undo){clearTimeout(toastTimer);$('#toastText').textContent=text;$('#toastUndo').hidden=!undo;undoAction=undo||null;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200)}

function bind(){
  document.addEventListener('click',async e=>{
    const nav=e.target.closest('[data-nav]');if(nav){currentView=nav.dataset.nav;render();window.scrollTo({top:0,behavior:'smooth'});return}
    const st=e.target.closest('[data-study-tab]');if(st){local.ui.studyTab=st.dataset.studyTab;saveLocal();renderStudy();return}
    const range=e.target.closest('[data-range]');if(range){local.ui.insightRange=range.dataset.range;saveLocal();renderInsights();return}
    const dateBtn=e.target.closest('[data-set-date]');if(dateBtn){$('#doneDate').value=dateBtn.dataset.setDate;$$('[data-set-date]').forEach(x=>x.classList.toggle('active',x===dateBtn));return}
    const minBtn=e.target.closest('[data-set-minutes]');if(minBtn){if($('#doneMinutes'))$('#doneMinutes').value=minBtn.dataset.setMinutes;return}
    const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
    if(a==='close-sheet')closeSheet();
    else if(a==='focus-picker')openFocusPicker();
    else if(a==='focus-preset')startFocus(Number(b.dataset.min),$('#focusPickSubject')?.value||'');
    else if(a==='focus-custom')startFocus(Number($('#focusCustomMin').value)||50,$('#focusPickSubject').value);
    else if(a==='historical')openDoneForm();
    else if(a==='add-plan')openPlanForm(b.dataset.bucket||'today');
    else if(a==='save-done')await saveDone(false);
    else if(a==='save-done-more')await saveDone(true);
    else if(a==='save-plan')await savePlan();
    else if(a==='plan-menu')openPlanMenu(b.dataset.id);
    else if(a==='edit-plan'){const p=mergedPlanBoard().find(x=>String(x.id)===String(b.dataset.id));if(p){const bucket=p.bucket==='day'?(p.date===isoDate(now())?'today':p.date===isoDate(addDays(now(),1))?'tomorrow':'date'):(p.bucket==='week'?(p.week_start===isoDate(addDays(startOfWeek(now()),7))?'next_week':'week'):'inbox');openPlanForm(bucket,p)}}
    else if(a==='delete-plan')await deletePlan(b.dataset.id);
    else if(a==='move-plan')await movePlan(b.dataset.id,b.dataset.dest);
    else if(a==='complete-plan')await completePlanById(b.dataset.id,b.dataset.external==='1');
    else if(a==='task-focus'){let p=b.dataset.external==='1'?plansForDay(isoDate(now())).find(x=>x.external&&String(x.id)===String(b.dataset.id)):mergedPlanBoard().find(x=>String(x.id)===String(b.dataset.id));if(p)startFocus(planMinutes(p)||50,p.subject,p.topic,p.activity||'專注','task',p.external?'':p.id)}
    else if(a==='next-focus'){const n=nextAction();startFocus(50,n.subject,n.topic,n.activity,'task',n.planId||'')}
    else if(a==='record-menu')openRecordMenu(b.dataset.source,b.dataset.id,b.dataset.kind);
    else if(a==='edit-record'){const r=allRecords().find(x=>x.source===b.dataset.source&&String(x.id)===String(b.dataset.id));if(r)openDoneForm({record:r,date:r.date})}
    else if(a==='delete-record')await deleteDoneRecord(b.dataset.id,b.dataset.source);
    else if(a==='add-question')openQuestionForm();
    else if(a==='question-menu')openQuestionMenu(b.dataset.id);
    else if(a==='edit-question')openQuestionForm(b.dataset.id);
    else if(a==='delete-question')await deleteQuestion(b.dataset.id);
    else if(a==='save-question')await saveQuestion();
    else if(a==='manual-progress')openManualProgress();
    else if(a==='save-manual')await saveManual();
    else if(a==='vocab-add')openVocabForm();
    else if(a==='vocab-menu')openVocabMenu(b.dataset.id);
    else if(a==='vocab-edit')openVocabForm(b.dataset.id);
    else if(a==='vocab-delete')await deleteVocab(b.dataset.id);
    else if(a==='save-vocab')await saveVocab();
    else if(a==='vocab-review')openVocabReview();
    else if(a==='grade-vocab')await gradeVocab(Number(b.dataset.grade));
    else if(a==='weekly-target')openWeeklyTarget();
    else if(a==='save-weekly-target')await saveWeeklyTargets();
    else if(a==='add-decision')openDecisionForm();
    else if(a==='save-decision')await saveDecision();
    else if(a==='course-focus')startFocus(50,b.dataset.subject,`${b.dataset.subject}_${b.dataset.code}_${b.dataset.topic}`,'看課','course');
    else if(a==='course-review')openDoneForm({subject:b.dataset.subject,topic:b.dataset.topic,activity:'複習',minutes:30});
    else if(a==='finish-review')finishReview(b.dataset.subject,b.dataset.topic);
    else if(a==='toggle-review')toggleReview();
    else if(a==='save-settings')saveSettingsFromForm();
    else if(a==='test-sync'){saveSettingsFromForm();await syncCloud(true)}
    else if(a==='export-backup')exportBackup();
    else if(a==='history'){closeSheet();currentView='study';local.ui.studyTab='history';saveLocal();render()}
    else if(a==='day-close')openDayClose();
    else if(a==='plan-mode'){local.ui.planMode=b.dataset.mode;saveLocal();renderPlan()}
    else if(a==='template')applyTemplate(b.dataset.template);
    else if(a==='insight-detail')openInsightDetail(b.dataset.type,b.dataset.key);
  });
  document.addEventListener('change',e=>{if(e.target.id==='courseSubject'){local.ui.courseSubject=e.target.value;saveLocal();renderStudyBody('courses')}});
  document.addEventListener('input',e=>{
    if(e.target.id==='courseSearch'){const q=e.target.value.toLowerCase(),subj=local.ui.courseSubject||'物理',items=trackedCourses().filter(x=>x.subject===subj&&`${x.code} ${x.topic}`.toLowerCase().includes(q));$('#courseGrid').innerHTML=courseCards(items)}
    if(e.target.id==='historySearch'||e.target.id==='historySubject'){const q=($('#historySearch')?.value||'').toLowerCase(),s=$('#historySubject')?.value||'',rows=doneRecords().slice().sort((a,b)=>(String(b.date)+String(b.start)).localeCompare(String(a.date)+String(a.start))).filter(r=>(!s||r.subject===s)&&(!q||`${r.date} ${r.subject} ${r.topic} ${r.activity}`.toLowerCase().includes(q)));$('#historyRows').innerHTML=historyRowsHTML(rows)}
    if(e.target.id==='globalSearchInput')$('#globalSearchResults').innerHTML=globalSearchHTML(e.target.value)
  });
  $('#quickAddBtn').onclick=openQuickMenu;$('#fabBtn').onclick=openQuickMenu;$('#sheetBackdrop').onclick=closeSheet;$('#syncBtn').onclick=()=>syncCloud(true);$('#syncBtnSide').onclick=()=>syncCloud(true);$('#themeBtn').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('#searchBtn').onclick=openGlobalSearch;
  $('#focusMinimize').onclick=()=>showFocus(true);$('#miniExpand').onclick=()=>showFocus(false);$('#focusPause').onclick=toggleFocusPause;$('#miniPause').onclick=toggleFocusPause;$('#focusPlus10').onclick=()=>addFocusMinutes(10);$('#focusPlus15').onclick=()=>addFocusMinutes(15);$('#focusFinish').onclick=()=>finishFocus(false);$('#miniFinish').onclick=()=>finishFocus(false);$('#focusCancel').onclick=cancelFocus;
  $('#toastUndo').onclick=async()=>{if(undoAction)await undoAction();undoAction=null;$('#toast').classList.remove('show')};
  document.addEventListener('click',e=>{if(e.target.closest('#flashcard'))e.target.closest('#flashcard').classList.add('revealed')});
  document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key.toLowerCase()==='n')openQuickMenu();if(e.key.toLowerCase()==='f')openFocusPicker();if(e.key==='/'){e.preventDefault();openGlobalSearch()}});
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&focus.running)requestWakeLock()});
}

function seedDemo(){if(!location.search.includes('demo=1'))return;const d=isoDate(now()),ws=isoDate(startOfWeek(now()));if(!local.planBoard.length)local.planBoard=[{id:'demo1',bucket:'day',date:d,week_start:ws,subject:'物理',activity:'看課',topic:'物理_027-1_電磁感應',planned_minutes:60,start_time:'09:00',status:'open',created_at:new Date().toISOString()},{id:'demo2',bucket:'day',date:d,week_start:ws,subject:'生化',activity:'看課',topic:'生化_014_蛋白質分析',planned_minutes:90,start_time:'14:00',status:'open',created_at:new Date().toISOString()},{id:'demo3',bucket:'week',date:'',week_start:ws,subject:'英文',activity:'英文閱讀',topic:'Vol.07 Day 01',planned_minutes:60,status:'open',created_at:new Date().toISOString()}];if(!cloud.quickLog.length)cloud.quickLog=[{event_id:'demoq1',date:d,type:'DONE',subject:'物理',activity:'看課',topic:'物理_026_運動電動勢',minutes:50,status:'完成',start_time:new Date(Date.now()-3*3600000).toISOString(),end_time:new Date(Date.now()-2.15*3600000).toISOString(),notes:'[focus]'},{event_id:'demoq2',date:d,type:'DONE',subject:'英文',activity:'英文閱讀',topic:'Vol.06 Day 08',minutes:35,status:'完成',start_time:new Date(Date.now()-1.5*3600000).toISOString(),end_time:new Date(Date.now()-.9*3600000).toISOString(),notes:'[focus]'}];if(!local.weeklyPlan.length)local.weeklyPlan=SUBJECTS.map((s,i)=>({id:`${ws}|${s}`,week_start:ws,subject:s,planned_minutes:[480,420,240,240,240][i]}));saveLocal();cacheCloud()}
async function init(){initTheme();loadCache();seedDemo();bind();render();loadFocus();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setTimeout(()=>syncCloud(false),350)}
init();
